AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'

Layout/AlignHash:
  Enabled: false

Style/NestedTernaryOperator:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Style/GlobalVars:
  Enabled: false