# test:
#   service: Disk
#   root: <%= Rails.root.join("tmp/storage") %>


aliyun:
  service: Aliyun
  access_key_id: LTAIGt0BBAlKBUv9
  access_key_secret: mjMc6mI3rBjvWE9MTIrw71Ydpqfoio
  bucket: duodu
  path: systems
  endpoint: https://oss-cn-beijing.aliyuncs.com
  mode: private

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>