# test:
#   service: Disk
#   root: <%= Rails.root.join("tmp/storage") %>


development:
  service: Aliyun
  access_key_id: LTAIGt0BBAlKBUv9
  access_key_secret: mjMc6mI3rBjvWE9MTIrw71Ydpqfoio
  bucket: duodu-storage
  path: dev
  endpoint: https://oss-cn-zhangjiakou.aliyuncs.com
  mode: private

staging: 
  service: Aliyun
  access_key_id: LTAIGt0BBAlKBUv9
  access_key_secret: mjMc6mI3rBjvWE9MTIrw71Ydpqfoio
  bucket: duodu-storage
  path: staging
  endpoint: https://oss-cn-zhangjiakou.aliyuncs.com
  mode: private

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>